"""widen command execution policy decision

Revision ID: 76a16fdad3cb
Revises: e7ccb76aebf6
Create Date: 2026-07-15 02:20:05.798919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76a16fdad3cb'
down_revision: Union[str, None] = 'e7ccb76aebf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('command_executions', 'policy_decision',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('command_executions', 'policy_decision',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
