"""v1: trust, leases, review findings, validation evidence

Revision ID: e7ccb76aebf6
Revises: 9991acc7e22f
Create Date: 2026-07-15 01:48:11.338726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7ccb76aebf6'
down_revision: Union[str, None] = '9991acc7e22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_findings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('reviewer', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file', sa.String(length=1000), nullable=True),
    sa.Column('line', sa.String(length=40), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_findings_run_id'), 'review_findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_review_findings_task_id'), 'review_findings', ['task_id'], unique=False)
    op.add_column('goals', sa.Column('plan_mode', sa.String(length=20), nullable=False, server_default='auto'))
    op.add_column('prompts', sa.Column('context_manifest', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('prompts', sa.Column('version', sa.String(length=20), nullable=False, server_default='v1'))
    op.add_column('repositories', sa.Column('remote_url', sa.String(length=500), nullable=True))
    op.add_column('repositories', sa.Column('github_slug', sa.String(length=300), nullable=True))
    op.add_column('repositories', sa.Column('trust_level', sa.String(length=30), nullable=False, server_default='untrusted'))
    op.add_column('repositories', sa.Column('validation_profile', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('repositories', sa.Column('languages', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('repositories', sa.Column('package_managers', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('repositories', sa.Column('protected_paths', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('repositories', sa.Column('onboarded', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('repositories', sa.Column('last_inspected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('meta', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('runs', sa.Column('purpose', sa.String(length=30), nullable=False, server_default='implementation'))
    op.add_column('runs', sa.Column('orchestrator_id', sa.String(length=80), nullable=True))
    op.add_column('runs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('usage', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('tasks', sa.Column('scope_globs', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('tasks', sa.Column('context', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('tasks', sa.Column('idempotency_key', sa.String(length=120), nullable=True))
    op.add_column('tasks', sa.Column('review_verdict', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['idempotency_key'])
    op.add_column('validation_results', sa.Column('status', sa.String(length=20), nullable=False, server_default='failed'))
    op.add_column('validation_results', sa.Column('command', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('validation_results', sa.Column('profile', sa.String(length=60), nullable=False, server_default=''))
    op.add_column('validation_results', sa.Column('exit_code', sa.Integer(), nullable=True))
    op.add_column('validation_results', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('validation_results', sa.Column('output_tail', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_results', 'output_tail')
    op.drop_column('validation_results', 'duration_ms')
    op.drop_column('validation_results', 'exit_code')
    op.drop_column('validation_results', 'profile')
    op.drop_column('validation_results', 'command')
    op.drop_column('validation_results', 'status')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'review_verdict')
    op.drop_column('tasks', 'idempotency_key')
    op.drop_column('tasks', 'context')
    op.drop_column('tasks', 'scope_globs')
    op.drop_column('runs', 'usage')
    op.drop_column('runs', 'heartbeat_at')
    op.drop_column('runs', 'lease_expires_at')
    op.drop_column('runs', 'orchestrator_id')
    op.drop_column('runs', 'purpose')
    op.drop_column('repositories', 'meta')
    op.drop_column('repositories', 'last_inspected_at')
    op.drop_column('repositories', 'onboarded')
    op.drop_column('repositories', 'protected_paths')
    op.drop_column('repositories', 'package_managers')
    op.drop_column('repositories', 'languages')
    op.drop_column('repositories', 'validation_profile')
    op.drop_column('repositories', 'trust_level')
    op.drop_column('repositories', 'github_slug')
    op.drop_column('repositories', 'remote_url')
    op.drop_column('prompts', 'version')
    op.drop_column('prompts', 'context_manifest')
    op.drop_column('goals', 'plan_mode')
    op.drop_index(op.f('ix_review_findings_task_id'), table_name='review_findings')
    op.drop_index(op.f('ix_review_findings_run_id'), table_name='review_findings')
    op.drop_table('review_findings')
    # ### end Alembic commands ###
